services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    platform: linux/amd64
    container_name: clinica_web
    ports:
      - "8083:80"
    volumes:
      - ./APP/VIEW:/var/www/html
      - ./APP/CONTROLLER:/var/www/CONTROLLER
      - ./APP/MODEL:/var/www/MODEL
      - ./APP/config:/var/www/config
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html