services:
  web:
    build: .
    container_name: clinica_web
    ports:
      - "8083:80"
    volumes:
      - ./APP:/var/www            # monta TODO APP (config, controllers, models, VIEW, etc.)
      - ./APP/VIEW:/var/www/html  # hace que el docroot sea tu carpeta VIEW
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - LD_LIBRARY_PATH=/opt/oracle/instantclient_23_26
      - NLS_LANG=AMERICAN_AMERICA.AL32UTF8